# **ch1. 헬로 파이썬**  
### 파이썬에 대해 알아보기  

<br/>  

- - -  

<br/>  

#### 1.4.2 클래스  
class를 정의하면 독자적인 data type을 만들 수 있음  
class에는 method(전용 함수)와 arrtibute를 정의할 수도 있음  


class의 구조  
> ```
> class class_name:
>    def __init__(self, factor, ...):    # constructor(생성자)
>        ...
>    def method_name_1(self, factor, ...):   # method1
>        ...
>    def method_name_2(self, factor, ...):   # method2
>        ...
>```


class의 definition에는 `__init__`이라는 method가 있는데, class를 initialize하는 방법을 정의함  
이 initialization용 method를 constructor라고 하며, class의 instance가 만들어질 때 한 번만 call됨  
python에서는 method의 첫 번째 factor로 자신(자신의 instance)을 나타내는 `self`를 명시적으로 씀  

<br/>

간단한 class 만들기



In [1]:
class Man:
    def __init__(self, name):
        self.name = name
        print('Initialized')

    def hello(self):
        print('Hello '+self.name+'!')
    
    def goodbye(self):
        print('Good-bye '+self.name+'!')

In [2]:
m = Man('David')
m.hello()
m.goodbye()

Initialized
Hello David!
Good-bye David!


`Man`이라는 class를 define하고, `m`이라는 instance(object)를 생성함  
`Man`의 constructor는 `name`이라는 factor를 받고, 해당 factor로 instance variance(instance별로 저장되는 variance)인 `self.name`를 initialize함  
python에서는 `self.name`처럼 `self`다음에 attribute 이름을 작성하여 instance variance를 만들거나 접근할 수 있음


<br/>  

- - -  

<br/>  

### *1.5 넘파이*  
deep learning을 구현할 때 array나 matrix를 많이 다루는데, numpy의 array class인 `numpy.class`에는 편리한 method가 많이 준비되어 있어 deep learning을 구현하는 데 많이 사용함

<br/>

#### 1.5.1 넘파이 가져오기  
numpy는 외부 library이므로 import해야 함

In [3]:
import numpy as np

numpy array를 만들 때에는 `np.array()` method를 사용함  
`np.array()`는 python list를 factor로 받아 numpy가 제공하는 특수한 형태의 array를 return함

In [4]:
x = np.array([1.0, 2.0, 3.0])
print(x)
print(type(x))

[1. 2. 3.]
<class 'numpy.ndarray'>


#### 1.5.3 넘파이의 산술 연산  
numpy array의 산술 연산

In [5]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)


[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


위 예시에서는 `x`와 `y`의 element 수가 같음  
&rarr; element 수가 같은 array에 대해서는 각 element에 대해서(element-wise) 산술 연산이 진행됨  
element 수가 다르면 error가 발생함  


numpy array는 element-wise 계산 뿐 아니라 numpy array와 scalar 사이의 연산도 수행할 수 있음  
이 경우, scalar와의 계산이 numpy array의 element 별로 한 번씩 수행됨  
&rarr; 이를 broadcasting이라고 함

In [6]:
x = np.array([1.0, 2.0, 3.0])

print(x/2.0)

[0.5 1.  1.5]


#### 1.5.4 넘파이의 N차원 배열  
numpy는 1 dimenson array뿐 아니라 multi dimension도 작성할 수 있음

In [7]:
a = np.array([[1, 2], [3, 4]])

print(a)

[[1 2]
 [3 4]]


array의 shape은 `shape`으로, element의 data dype은 `dtype`으로 확인할 수 있음

In [8]:
print(a.shape)
print(a.dtype)

(2, 2)
int64


multi dimension array의 산술 연산도 앞선 1 dimension array와 마찬가지로 대응하는 element 별로 계산됨 multi dimension array와 scalar의 연산도 가능함(broadcasting)

In [9]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 0], [0, 6]])

print(a+b)
print(a*b)
print(a*10)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]
[[10 20]
 [30 40]]


#### 1.5.5 브로드캐스트  
numpy에서는 shape이 다른 array끼리도 연산을 수행할 수 있음  
앞선 예시에서 2x2 array(matrix)인 `a`에 scalar value인 10을 곱했음  
&rarr; 이 때, 10이라는 scalar value가 matrix로 확대되어 연산이 수행됨  
&rarr; 이를 broadcasting이라고 함

<br/>

shape이 다른 array 간의 예시

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

print(a*b)

[[10 40]
 [30 80]]


이 예에서는 1 dimension array(vector)인 `b`가 `a`와 같은 matrix의 shape으로 변환된 후 element-wise 연산이 수행됨

<br/>

#### 1.5.6 원소 접근  
element의 index는 0부터 시작함  

<br/>

각 element에 access하려면 다음과 같이 함

In [11]:
x = np.array([[51, 55], [14, 19], [0, 4]])

print(x)
print(x[0])
print(x[0][1])

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55


`for`문을 사용하여 각 element에 access할 수도 있음

In [12]:
for row in x:
    print(row)

[51 55]
[14 19]
[0 4]


numpy는 index를 array로 지정해 한 번에 여러 element에 access할 수도 있음

In [13]:
x = x.flatten()

print(x[np.array([0, 2, 4])])

[51 14  0]


이러한 방법을 활용하면 특정 condition을 만족하는 element만 얻을 수 있음

<br/>

다음과 같이 value가 15이상인 element만 얻을 수도 있음

In [15]:
print(x>15)

print(x[x>15])

[ True  True False  True False False]
[51 55 19]


numpy array에 comparison operator를 사용한 결과는 boolean array  
위 예에서는 boolean array를 사용해 `x`에서 `True`에 해당하는 element만 꺼낸 것

<br/>

